version: '3.8'

services:
  smma:
    build: .
    container_name: smma
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PATH=/app/data/hodler.db
