/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search tickers by name or symbol
         * @description Search Yahoo Finance by company name, ticker symbol or **ISIN**
         *     (e.g. `Apple`, `MC.PA`, `FR0000121014`). Fuzzy matching tolerates typos.
         */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ticker/{ticker_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full technical analysis of a ticker
         * @description Return all technical indicators + B&H score for a ticker.
         *
         *     **Examples**: `MC.PA`, `AAPL`, `ASML.AS`, `BTC-USD`
         *
         *     - `refresh=true`: force recomputation even if the cache is valid
         *     - `lang`: language of the analysis text (`en` by default, `fr`)
         */
        get: operations["get_ticker_ticker__ticker_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ticker/{ticker_code}/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historical data for charts
         * @description Return price, SMA 200/50, RSI 14 and MACD histogram for the charts.
         */
        get: operations["ticker_chart_ticker__ticker_code__chart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ticker/{ticker_code}/fundamentals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fundamental data
         * @description P/E, market cap, sector, country via yfinance.info.
         */
        get: operations["ticker_fundamentals_ticker__ticker_code__fundamentals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ticker/{ticker_code}/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent news
         * @description Latest news for the stock via yfinance (Yahoo Finance).
         */
        get: operations["ticker_news_ticker__ticker_code__news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ticker/{ticker_code}/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Light score backtest
         * @description Replay the Buy & Hold score over ~5 years of history and report the realized
         *     forward returns (≈3M / 6M / 12M) grouped by score band — a credibility check
         *     on the scoring engine.
         */
        get: operations["ticker_backtest_ticker__ticker_code__backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cache state
         * @description List cached entries with their age and remaining TTL.
         */
        get: operations["cache_info_cache_get"];
        put?: never;
        post?: never;
        /** Clear the entire cache */
        delete: operations["cache_clear_cache_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cache/{ticker_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Invalidate a ticker */
        delete: operations["cache_invalidate_cache__ticker_code__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear selected caches and DB data
         * @description Selectively wipe in-memory caches and DB rows per data type.
         *
         *     Each flag is opt-in: ``caches`` (in-memory analyses/charts/news…),
         *     ``watchlist`` (favorites), ``portfolio`` (positions), ``backtests``
         *     (stored score history) and ``tickers`` (the name/ISIN dictionary).
         */
        post: operations["reset_all_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List favorites
         * @description Return the watchlist persisted server-side.
         */
        get: operations["favorites_list_favorites_get"];
        /**
         * Replace the entire favorites list
         * @description Fully replace the watchlist (used for import/migration).
         */
        put: operations["favorites_set_favorites_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/{ticker_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a favorite */
        post: operations["favorites_add_favorites__ticker_code__post"];
        /** Remove a favorite */
        delete: operations["favorites_remove_favorites__ticker_code__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Portfolio with live valuation
         * @description Return every stored position enriched with its live price, P&L and weight.
         */
        get: operations["portfolio_get_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/{ticker_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Add or update a position
         * @description Insert or update a position (one aggregated lot per ticker).
         */
        put: operations["portfolio_upsert_portfolio__ticker_code__put"];
        post?: never;
        /** Remove a position */
        delete: operations["portfolio_remove_portfolio__ticker_code__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze a list of tickers
         * @description Analyze several tickers in parallel.
         *
         *     ```json
         *     { "tickers": ["MC.PA", "ASML.AS", "AIR.PA"], "refresh": false, "lang": "en" }
         *     ```
         *
         *     Each entry in the result contains either the data or an `error` field.
         */
        post: operations["post_tickers_tickers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Analysis */
        Analysis: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Timestamp */
            timestamp: string;
            /** Data Partiel */
            data_partiel: boolean;
            /** Days Available */
            days_available: number;
            price: components["schemas"]["AnalysisPrice"];
            indicators: components["schemas"]["AnalysisIndicators"];
            distances: components["schemas"]["AnalysisDistances"];
            fundamentals: components["schemas"]["AnalysisFundamentals"];
            signals: components["schemas"]["AnalysisSignals"];
            analysis: components["schemas"]["AnalysisBlock"];
            /** Cached */
            cached?: boolean | null;
        };
        /** AnalysisBlock */
        AnalysisBlock: {
            /** Score */
            score: number;
            /** Score Details */
            score_details: {
                [key: string]: number;
            };
            /** Statut */
            statut: string;
            synthese: components["schemas"]["AnalysisSynthese"];
            /** Explication */
            explication: string;
            /** Strategie */
            strategie: string;
            /** Objectifs */
            objectifs: string;
            /** Diagnostics */
            diagnostics: components["schemas"]["Diagnostic"][];
        };
        /** AnalysisDistances */
        AnalysisDistances: {
            /** Ecart Sma200 Pct */
            ecart_sma200_pct: number;
            /** Ecart W50 Pct */
            ecart_w50_pct?: number | null;
            /** Dist 52W High Pct */
            dist_52w_high_pct: number;
            /** Dist 52W Low Pct */
            dist_52w_low_pct: number;
            /** H52W Price */
            h52w_price: number;
            /** L52W Price */
            l52w_price: number;
        };
        /** AnalysisFundamentals */
        AnalysisFundamentals: {
            /** Dividende Annuel */
            dividende_annuel: number;
            /** Derniere Date Div */
            derniere_date_div: string;
        };
        /** AnalysisIndicators */
        AnalysisIndicators: {
            /** Sma200 */
            sma200: number;
            /** Sma50 */
            sma50: number;
            /** W50 */
            w50?: number | null;
            /** Sma200 Slope 20J Pct */
            sma200_slope_20j_pct: number;
            /** Rsi Daily */
            rsi_daily: number;
            /** Rsi Weekly */
            rsi_weekly: number;
            /** Rvol */
            rvol: number;
            /** Bb Pct */
            bb_pct: number;
            /** Macd W Hist */
            macd_w_hist: number;
            /** Macd W Hist Prev */
            macd_w_hist_prev: number;
            /** Macd W Cross Up */
            macd_w_cross_up: boolean;
            /** Atr14 */
            atr14: number;
            /** Atr14 Pct */
            atr14_pct: number;
            /** Adx14 */
            adx14: number;
            /** Chop14 */
            chop14: number;
        };
        /** AnalysisPrice */
        AnalysisPrice: {
            /** Last */
            last: number;
            /** Var Jour Pct */
            var_jour_pct: number;
        };
        /** AnalysisSignals */
        AnalysisSignals: {
            /** Tendance */
            tendance: string;
            regime: components["schemas"]["MarketRegime"];
            /** Alerte Sma200 */
            alerte_sma200: boolean;
            /** Alerte W50 */
            alerte_w50: boolean;
            /** Divergence Rsi */
            divergence_rsi: boolean;
            /** Rsi Creux */
            rsi_creux?: [
                number,
                number
            ] | null;
        };
        /** AnalysisSynthese */
        AnalysisSynthese: {
            /** Verdict */
            verdict: string;
            /** Atout */
            atout?: string | null;
            /** Risque */
            risque?: string | null;
        };
        /** BacktestReport */
        BacktestReport: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Period Start */
            period_start: string;
            /** Period End */
            period_end: string;
            /** Samples */
            samples: number;
            /** Horizons Days */
            horizons_days: number[];
            /** Primary Horizon */
            primary_horizon: number;
            /** Series */
            series: components["schemas"]["BacktestSeriesPoint"][];
            /** Bands */
            bands: components["schemas"]["ScoreBand"][];
            baseline: components["schemas"]["Baseline"];
            /** Correlation */
            correlation: {
                [key: string]: number | null;
            };
            timing: components["schemas"]["Timing"];
            /** Cached */
            cached: boolean;
        };
        /** BacktestSeriesPoint */
        BacktestSeriesPoint: {
            /** Date */
            date: string;
            /** Price */
            price: number;
            /** Score */
            score?: number | null;
            /** Sma200 */
            sma200?: number | null;
        };
        /**
         * BandKey
         * @enum {string}
         */
        BandKey: "strong" | "accumulate" | "watch" | "avoid";
        /** Baseline */
        Baseline: {
            /** Avg Return */
            avg_return?: number | null;
            /** Win Rate */
            win_rate?: number | null;
            /** By Horizon */
            by_horizon: {
                [key: string]: components["schemas"]["HorizonStats"];
            };
        };
        /** ChartData */
        ChartData: {
            /** Dates */
            dates: string[];
            /** Close */
            close: (number | null)[];
            /** Sma200 */
            sma200: (number | null)[];
            /** Sma50 */
            sma50: (number | null)[];
            /** Rsi */
            rsi: (number | null)[];
            /** Macd Hist */
            macd_hist: (number | null)[];
            /** Volume */
            volume: (number | null)[];
            /** Vol Sma20 */
            vol_sma20: (number | null)[];
            /** Bb Upper */
            bb_upper: (number | null)[];
            /** Bb Lower */
            bb_lower: (number | null)[];
        };
        /** Diagnostic */
        Diagnostic: {
            /** Text */
            text: string;
            /** Impact */
            impact: number;
        };
        /** FavoritesImport */
        FavoritesImport: {
            /** Tickers */
            tickers: string[];
        };
        /** FavoritesResponse */
        FavoritesResponse: {
            /** Favorites */
            favorites: string[];
            /** Added */
            added?: boolean | null;
            /** Removed */
            removed?: boolean | null;
        };
        /** Fundamentals */
        Fundamentals: {
            /** Pe Trailing */
            pe_trailing?: number | null;
            /** Pe Forward */
            pe_forward?: number | null;
            /** Market Cap */
            market_cap?: number | null;
            /** Sector */
            sector: string;
            /** Industry */
            industry: string;
            /** Country */
            country: string;
            /** Employees */
            employees?: number | null;
            /** Earnings Date */
            earnings_date?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HorizonStats */
        HorizonStats: {
            /** Count */
            count: number;
            /** Avg Return */
            avg_return?: number | null;
            /** Median Return */
            median_return?: number | null;
            /** Win Rate */
            win_rate?: number | null;
        };
        /**
         * MarketRegime
         * @enum {string}
         */
        MarketRegime: "trend_up" | "trend_down" | "range" | "transition";
        /** News */
        News: {
            /** Ticker */
            ticker: string;
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["NewsItem"][];
        };
        /** NewsItem */
        NewsItem: {
            /** Title */
            title: string;
            /** Publisher */
            publisher?: string | null;
            /** Url */
            url: string;
            /** Published */
            published?: string | null;
            /** Thumbnail */
            thumbnail?: string | null;
        };
        /** Portfolio */
        Portfolio: {
            /** Positions */
            positions: components["schemas"]["Position"][];
            totals: components["schemas"]["PortfolioTotals"];
        };
        /** PortfolioTotals */
        PortfolioTotals: {
            /** Cost */
            cost: number;
            /** Value */
            value: number;
            /** Pnl */
            pnl: number;
            /** Pnl Pct */
            pnl_pct?: number | null;
            /** Count */
            count: number;
            /** Priced */
            priced: boolean;
        };
        /** Position */
        Position: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Avg Cost */
            avg_cost: number;
            /** Price */
            price?: number | null;
            /** Cost */
            cost: number;
            /** Value */
            value?: number | null;
            /** Pnl */
            pnl?: number | null;
            /** Pnl Pct */
            pnl_pct?: number | null;
            /** Weight */
            weight?: number | null;
            /** Note */
            note?: string | null;
        };
        /** PositionBody */
        PositionBody: {
            /** Quantity */
            quantity: number;
            /** Avg Cost */
            avg_cost: number;
            /** Note */
            note?: string | null;
        };
        /** ResetBody */
        ResetBody: {
            /**
             * Caches
             * @default false
             */
            caches: boolean;
            /**
             * Watchlist
             * @default false
             */
            watchlist: boolean;
            /**
             * Portfolio
             * @default false
             */
            portfolio: boolean;
            /**
             * Backtests
             * @default false
             */
            backtests: boolean;
            /**
             * Tickers
             * @default false
             */
            tickers: boolean;
        };
        /** ScoreBand */
        ScoreBand: {
            key: components["schemas"]["BandKey"];
            /** Min */
            min: number;
            /** Count */
            count: number;
            /** Avg Return */
            avg_return?: number | null;
            /** Median Return */
            median_return?: number | null;
            /** Win Rate */
            win_rate?: number | null;
            /** By Horizon */
            by_horizon: {
                [key: string]: components["schemas"]["HorizonStats"];
            };
        };
        /** SearchResult */
        SearchResult: {
            /** Ticker */
            ticker: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Exchange */
            exchange: string;
        };
        /** TickerListRequest */
        TickerListRequest: {
            /** Tickers */
            tickers: string[];
            /**
             * Refresh
             * @default false
             */
            refresh: boolean;
            /**
             * Lang
             * @default en
             */
            lang: string;
        };
        /** Timing */
        Timing: {
            /** Current Score */
            current_score: number;
            /** Percentile */
            percentile: number;
            band: components["schemas"]["BandKey"];
            /** Edge */
            edge?: number | null;
            /** Engine Edge */
            engine_edge?: number | null;
            /** Correlation */
            correlation?: number | null;
            /** Horizon */
            horizon: number;
            /** Reliable */
            reliable: boolean;
            level: components["schemas"]["TimingLevel"];
        };
        /**
         * TimingLevel
         * @enum {string}
         */
        TimingLevel: "excellent" | "good" | "fair" | "poor" | "unreliable";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticker_ticker__ticker_code__get: {
        parameters: {
            query?: {
                refresh?: boolean;
                lang?: string;
            };
            header?: never;
            path: {
                ticker_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Analysis"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ticker_chart_ticker__ticker_code__chart_get: {
        parameters: {
            query?: {
                period?: string;
                refresh?: boolean;
            };
            header?: never;
            path: {
                ticker_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChartData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ticker_fundamentals_ticker__ticker_code__fundamentals_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                ticker_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fundamentals"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ticker_news_ticker__ticker_code__news_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                ticker_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["News"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ticker_backtest_ticker__ticker_code__backtest_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path: {
                ticker_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cache_info_cache_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    cache_clear_cache_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    cache_invalidate_cache__ticker_code__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_all_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    favorites_list_favorites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoritesResponse"];
                };
            };
        };
    };
    favorites_set_favorites_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FavoritesImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoritesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    favorites_add_favorites__ticker_code__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoritesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    favorites_remove_favorites__ticker_code__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoritesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_get_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
        };
    };
    portfolio_upsert_portfolio__ticker_code__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker_code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_remove_portfolio__ticker_code__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_tickers_tickers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TickerListRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
